variable "project" {
  type        = string
  default     = "quant-cloud-assignment"
  description = "Project name prefix"
}

variable "aws_region" {
  type        = string
  default     = "eu-north-1" # pick a free-tier friendly region
}

variable "frontend_bucket_name" {
  type        = string
  default     = null
  description = "Optional: predefine S3 bucket name (otherwise autogenerated)"
}